AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function deploy for bulk onboard
Parameters:
  Bucket:
    Type: String
    MinLength: 3
    MaxLength: 63
    Default: clumio-bulk-onboarding
    Description: The bucket name where the zip file is placed.
  CrossAccountLambdaRole:
    Type: String
    Default: CrossAccountClumioLambdaCFTRole
    Description: The name of the cross-account role that the lambda function will assume.
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: clumio-bulk-onboard-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowCFTActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowCFTCreation
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:RequestTag/Deployment: 'Clumio'
              - Sid: AllowCFTDeletion
                Effect: Allow
                Action:
                  - cloudformation:DeleteStack
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceTag/Deployment: 'Clumio'
        - PolicyName: AssumeRole-AWSCloudFormationStackExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: !Sub arn:aws:iam::*:role/${CrossAccountLambdaRole}
                Action:
                  - sts:AssumeRole
                Condition:
                  StringEquals:
                    sts:ExternalId: !Sub ${AWS::AccountId}
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaRole
    Properties:
      FunctionName: clumio-bulk-onboard-aws-accounts
      Runtime: python3.12
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      Handler: clumio_connect_aws_account.lambda_handler
      Code:
        S3Bucket: !Ref Bucket
        S3Key: clumio_bulk_onboarding.zip
      Description: Connect AWS account to Clumio.
      TracingConfig:
        Mode: Active
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokeScopedAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:clumio-bulk-onboard-aws-accounts:*
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:clumio-bulk-onboard-aws-accounts
  BulkRestoreStepFunction:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: clumio-bulk-restore-state-machine
      RoleArn: !GetAtt StateMachineRole.Arn
      DefinitionString:
        Fn::Sub: |
            {
              "Comment": "This is a state machine to onboard AWS accounts to Clumio.",
              "StartAt": "Parse Input Data",
              "States": {
                "Parse Input Data": {
                  "Type": "Map",
                  "ItemProcessor": {
                    "ProcessorConfig": {
                      "Mode": "INLINE"
                    },
                    "StartAt": "Set lambda input",
                    "States": {
                      "Set lambda input": {
                        "Type": "Pass",
                        "Next": "clumio account onboard lambda",
                        "Parameters": {
                          "startTime.$": "$$.Execution.StartTime",
                          "execName.$": "$$.Execution.Name",
                          "bear.$": "$$.Execution.Input.bear",
                          "api_url.$": "$$.Execution.Input.api_url",
                          "stack_name.$": "$$.Execution.Input.stack_name",
                          "connection_detail.$": "$",
                          "cross_acocunt_cloudformation_role_name.$": "$$.Execution.Input.cross_acocunt_cloudformation_role_name"
                        }
                      },
                      "clumio account onboard lambda": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::lambda:invoke",
                        "OutputPath": "$.Payload",
                        "Parameters": {
                          "Payload.$": "$",
                          "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:clumio-bulk-onboard-aws-accounts:$LATEST"
                        },
                        "Retry": [
                          {
                            "ErrorEquals": [
                              "Lambda.ServiceException",
                              "Lambda.AWSLambdaException",
                              "Lambda.SdkClientException",
                              "Lambda.TooManyRequestsException"
                            ],
                            "IntervalSeconds": 1,
                            "MaxAttempts": 3,
                            "BackoffRate": 2
                          }
                        ],
                        "End": true
                      }
                    }
                  },
                  "End": true,
                  "ItemsPath": "$.connections"
                }
              }
            }
